# YAML Config file for RTM-QL agent

learning_params:
  gamma: 1
  learning_rate: 1
  EDF:
    epsilon_min: 0.01
    epsilon_max: 1
    epsilon_decay: 0.99
  SEDF:
    tail: 0.4
    slope: 0.3
    tail_gradient: 0.3
  epsilon_decay_function: SEDF 

memory_params:
  memory_size: 10000
  batch_size: 300

game_params:
  episodes: 200
  reward: 1
  max_score: -200
  min_score: 0
  action_space: 3

qrtm_params:
  # number_of_features = num_inputs [in this case, 4] * feature_length ALWAYS
  number_of_features: 8
  feature_length: 4
  # number_of_clauses = 2 * T ALWAYS
  number_of_clauses: 200
  T: 100
  s: 5
  incremental: True
  weighted_clauses: False
  # Set as multiple of number_of_features
  ta_states: 3

preproc_params:
  # Binarizer has to be a string 
  # G: Greater Than binarizer 
  # B: Binned binarizer
  # Q: Quartile binarizer
  # U: Unsigned binarizer
  # S: Simple binarizer ** DEFAULT feature length should be set to 2 and number of features to 8
  binarizer: U
