# YAML Config file for RTM-QL agent

learning_params:
  gamma: 0.99
  learning_rate: 0.5
  EDF:
    epsilon_min: 0.01
    epsilon_max: 0.5
    epsilon_decay: 0.99
  SEDF:
    tail: 0.4
    slope: 0.3
    tail_gradient: 0.3
  epsilon_decay_function: SEDF 

memory_params:
  memory_size: 10000
  batch_size: 300

game_params:
  episodes: 3000
  reward: 1
  max_score: 100
  min_score: -100
  action_space: [0,2]

qrtm_params:
  # number_of_features = num_inputs [in this case, 4] * feature_length ALWAYS
  number_of_features: 16
  feature_length: 8
  # number_of_clauses = 2 * T ALWAYS
  number_of_clauses: 20
  T: 1
  s: 5
  incremental: True
  weighted_clauses: False
  # Set as multiple of number_of_features
  ta_states: 4

preproc_params:
  # Binarizer has to be a string 
  # G: Greater Than binarizer 
  # B: Binned binarizer
  # Q: Quartile binarizer
  # U: Unsigned binarizer
  # S: Simple binarizer ** DEFAULT feature length should be set to 2 and number of features to 8
  binarizer: U
